version: '3.8'
services:
  dbserver:
    container_name: ba_back_mysql8
    env_file:
      - ./src/.env
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./src/scripts/sql:/docker-entrypoint-initdb.d
    restart: always
    ports:
      - 8082:3306
    networks:
      - ba_ntw
  backserver:
    container_name: ba_back_php73
    image: clemrz/bitcoin-analyzer-back:prod
    build:
      context: ./
    volumes:
      - ./src:/var/www/html/
      - ./log:/var/log/
    ports:
      - 80:80
    depends_on:
      - dbserver
    networks:
      - ba_ntw
  migrations:
    container_name: ba_back_migrations
    image: clemrz/bitcoin-analyzer-back:prod
    command: ./scripts/wait-for-it.sh ba_back_mysql8:3306 -- php scripts/run.php initialize
    depends_on:
      - dbserver
      - backserver
    networks:
      - ba_ntw
  cron:
    container_name: ba_back_cron
    image: clemrz/bitcoin-analyzer-back:prod
    entrypoint: ./scripts/wait-for-it.sh ba_back_php73:80 -- sh ./scripts/crontab.sh
    depends_on:
      - backserver
    volumes:
      - ./log:/var/log/
    networks:
      - ba_ntw

networks:
  ba_ntw:
    driver: bridge